version: '3.3'

services:
   nginx:
     image: nginx:stable
     volumes:
       - /home/vagrant/VOLUMES/NGINX/HTML:/usr/share/nginx/html
       - /home/vagrant/Provision/nginx/ressources/default.conf:/etc/nginx/conf.d/default.conf
     restart: always
     ports:
       - "8081:80"