version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - /home/vagrant/VOLUMES/WORDPRESS/SQL-DB:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: TO_CHANGE_IMMEDIATLY
       MYSQL_USER: TO_CHANGE
       MYSQL_PASSWORD: TO_CHANGE
       MYSQL_DATABASE: oOoOo

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "8080:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: TO_CHANGE
       WORDPRESS_DB_PASSWORD: TO_CHANGE
       WORDPRESS_DB_NAME: oOoOo