Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.box_version = "1.9.6"
  config.vm.network "private_network", ip:"192.168.2.23"
  config.vm.network "forwarded_port", guest: 80, host: 1996
  config.vm.network "forwarded_port", guest: 2004, host: 2004
  config.vm.hostname = "VM1"
  config.vm.provision "file", source: "VM1_Provisioning", destination:"~/"
  config.vm.provision "shell", inline: <<-SHELL
    cd /home/vagrant/VM1_Provisioning
    ./AUTOEXEC_dockerInstaller.sh
  SHELL
end
