Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian9"
  config.vm.box_version = "1.9.6"
  config.vm.network "private_network", ip:"192.168.2.23"
  config.vm.network "forwarded_port", guest: 80, host: 1996
  config.vm.network "forwarded_port", guest: 8080, host: 2004
  config.vm.hostname = "VM1"
  config.vm.provision "file", source: "Provision", destination:"/home/vagrant/"
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
	  cd ~/Provision
    ./AUTOEXEC.sh

    echo "you need to \"cd ~/Provision/nginx\" then \"sudo ./run.sh\""
    echo "then do the same with wordpress but fill passwords in docker-compose file"
  SHELL
end
